package codegen

var templateBase = `// Code generated by sparkle. DO NOT EDIT.
{{$engine := .}}
package {{ .PackageName }}

import (
	"math/big"
	"bytes"
{{- if .HasDynamicTemplate }}
	"encoding/json"
{{- end }}
	"fmt"
	"reflect"
	"time"

	"github.com/streamingfast/sparkle/subgraph"
	"github.com/streamingfast/sparkle/entity"
	eth "github.com/streamingfast/eth-go"
	pbcodec "github.com/streamingfast/sparkle/pb/sf/ethereum/codec/v1"

)
`
