package codegen

var templateHandler = `
{{$engine := .}}
package {{ .PackageName }}

import (
	pbcodec "github.com/streamingfast/sparkle/pb/dfuse/ethereum/codec/v1"
)

func (s *Subgraph) {{ $engine.ToCamelCase .CurrentHandlerName}}(ev *{{ .CurrentEvent }}Event) error {
	panic("code skeleton generated by sparkle. implement me")
}
`
