package codegen

var templateMerge = `
// Code generated by sparkle.
{{$engine := .}}
package {{ .PackageName }}

{{ range .Entities }}
//func ({{ $engine.FirstLetter .Name }} *{{ .Name }}) IsFinal(blockNum uint64, blockTime time.Time) bool {
//	//uncomment and implement if necessary
//}

{{ end }}
`
