package testgraph

func (s *Subgraph) Init() error {
	return nil // Code segment generated by sparkle. Edit if necessary.
}

func (s *Subgraph) LogStatus() {
	return // Code segment generated by sparkle. Edit if necessary.
}
